CREATE DATABASE IF NOT EXISTS moviecatalogue;


USE moviecatalogue;
CREATE TABLE Genre
    (GenreID INT AUTO_INCREMENT PRIMARY KEY, 
    GenreName VARCHAR(30) NOT NULL);

CREATE TABLE Director
    (DirectorID INT AUTO_INCREMENT PRIMARY KEY, 
    FIRSTNAME VARCHAR(30) NOT NULL, 
    LASTNAME VARCHAR(30) NOT NULL, 
    BirthDate DATE);

CREATE TABLE Rating
    (RatingID INT AUTO_INCREMENT PRIMARY KEY, RatingName VARCHAR(5) NOT NULL);

CREATE TABLE Movie
    (MovieID INT AUTO_INCREMENT PRIMARY KEY, 
    GenreID INT NOT NULL, 
    DirectorID INT, RatingID INT, 
    Title VARCHAR(128) NOT NULL, 
    ReleaseDate DATE, 
    FOREIGN KEY (GenreID) REFERENCES Genre(GenreID),
    FOREIGN KEY (DirectorID) REFERENCES Director(DirectorID),
    FOREIGN KEY (RatingID) REFERENCES Rating(RatingID)
);
CREATE TABLE Actor
    (ActorID INT AUTO_INCREMENT PRIMARY KEY,  
    FIRSTNAME VARCHAR(30) NOT NULL, 
    LASTNAME VARCHAR(30) NOT NULL, 
    BirthDate DATE);

CREATE TABLE CastMembers
    (CastMemberID INT AUTO_INCREMENT PRIMARY KEY,
    ActorID INT, 
    MovieID INT, 
    Role VARCHAR(50) NOT NULL,
    FOREIGN KEY (ActorID) REFERENCES Actor(ActorID),
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID)
);



INSERT INTO Director (DirectorID, FIRSTNAME, LASTNAME, BirthDate) 
VALUES(1, 'Ivan', 'Reitman', '1946-10-27');